# Site

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: nayo
# Home page setting
index_generator:
  path: ''
  per_page: 6  # 首页一页文章数量
  order_by: -date

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8  # 归档页一页文章数量
pagination_dir: page

# Writing
highlight:
  enable: true
  line_number: false # 代码高亮的行号
  auto_detect: true
  tab_replace:

# 上文提到的搜索功能增加的配置
search:
  path: search.xml
  field: post
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:HiraethEcho/hexo.git
  branch : hexo
